### ISSUE TITLE
Pylint E0401 import-error errors on test_paths_edges.py and test_paths_metadata.py

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/pathfinder#2]
Running the unit/integration tests on a daily basis reported the following errors on pathfinder since Nov, 8th.

```

176lint installed: astroid==2.8.3,backcall==0.1.0,backports.entry-points-selectable==1.1.0,click==7.1.1,coverage==6.0.2,decorator==4.4.2,distlib==0.3.3,docopt==0.6.2,docutils==0.18,filelock==3.3.1,Flask==1.1.2,Flask-Cors==3.0.8,Flask-SocketIO==4.2.1,importlib-metadata==4.8.1,importlib-resources==5.3.0,ipython==7.13.0,ipython-genutils==0.2.0,isort==5.9.3,itsdangerous==1.1.0,janus==0.4.0,jedi==0.16.0,Jinja2==2.11.1,-e git+https://github.com/kytos/kytos.git@3b9731c08fe7550a27d159f4e2de71419c9445f1#egg=kytos,-e git+https://github.com/kytos-ng/pathfinder@eb7784a88adec7d1d7f635b31389cf903a08e996#egg=kytos_pathfinder,lazy-object-proxy==1.6.0,lockfile==0.12.2,MarkupSafe==1.1.1,mccabe==0.6.1,networkx==2.5.1,packaging==21.0,parso==0.6.2,pathtools==0.1.2,pep517==0.12.0,pexpect==4.8.0,pickleshare==0.7.5,pip-tools==6.4.0,platformdirs==2.4.0,pluggy==1.0.0,prompt-toolkit==3.0.5,ptyprocess==0.6.0,py==1.10.0,pycodestyle==2.8.0,Pygments==2.10.0,PyJWT==1.7.1,pylint==2.11.1,pyparsing==2.4.7,python-daemon==2.2.4,python-engineio==3.12.1,-e git+https://github.com/kytos-ng/pathfinder@eb7784a88adec7d1d7f635b31389cf903a08e996#egg=python_openflow,python-socketio==4.5.1,six==1.16.0,toml==0.10.2,tomli==1.2.1,tox==3.24.4,traitlets==4.3.3,typed-ast==1.4.3,typing-extensions==3.10.0.2,virtualenv==20.8.1,watchdog==0.10.2,wcwidth==0.1.9,Werkzeug==1.0.1,wrapt==1.13.2,yala==3.0.1,zipp==3.6.0
177lint run-test-pre: PYTHONHASHSEED='3313558941'
178lint run-test: commands[0] | python setup.py lint
179running lint
180INFO: Finished isort
181INFO: Finished pycodestyle
182INFO: Finished pylint
183[isort] Skipped 5 files
184tests/integration/test_paths_edges.py|4:0|Unable to import 'tests.integration.edges_settings' (E0401, import-error) [pylint]
185tests/integration/test_paths_metadata.py|4:0|Unable to import 'tests.integration.metadata_settings' (E0401, import-error) [pylint]
186:( 2 issues found.
```

The pipeline is quite simple:
```
image: "python:3.6"

stages:
  - test

variables:
  PROJECT: "pathfinder"

run-tests:
  stage: test
  allow_failure: true
  script:
    - apt-get update -y && apt-get upgrade -y
    - pip install --upgrade pip tox
    - git clone https://github.com/kytos-ng/$PROJECT
    - cd $PROJECT
    - tox
```

Date which this issue started happening matches PR #1. I'm just not sure why travis-ci didn't detect this.
